# Generated by Django 5.0.4 on 2024-05-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_productvarient_delete_muhammadmuhsin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
